### ISSUE TITLE
Unable to build the tofita, due to error

### ISSUE THREAD

**Issue by mnisk** [GreenteaOS/Tofita#1]
I just tried to compile the tofita kernel but it shows the error in :-
boot/uefi/boot.c:113:4: error : use of undeclared identifier 'bootsvc'

**Screenshots**

![Screenshot (5409)](https://user-images.githubusercontent.com/49841018/57004515-301ae180-6bed-11e9-9ca5-f8768568bdab.png)

**Comment by PeyTy** [comment]
@Manish-Kala-Jaat Will be buildable ASAP

**Comment by PeyTy** [comment]
@mnisk hello, check again

**Comment by PeyTy** [comment]
Note: you should use Wine to run build.bat
