### ISSUE TITLE
Use GitHub Actions for builds

### ISSUE THREAD

**Issue by PeyTy** [GreenteaOS/Tofita#11]
### Is your feature request related to a Tofita kernel specifically? Please describe

Do it ASAP

### Describe the solution you'd like

This should work the same way as AppVeyor does for now

### Describe the possible impacts for the developers and users

Better GitHub integration

### Agreements

- [X] I agree to follow this project's [__Contributing Guidelines__](https://github.com/GreenteaOS/.github/blob/kawaii/CONTRIBUTING.md)
- [X] I agree to follow this project's [__Code of Conduct__](https://github.com/GreenteaOS/.github/blob/kawaii/CODE_OF_CONDUCT.md)

**Comment by acidicMercury8** [comment]
@PeyTy this issue can already be closed, because the pipelines are synchronized and allow to conveniently generate ISO images
